# Generated by Django 4.2
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # ── Tabelas de domínio ────────────────────────────────────────
        migrations.CreateModel(
            name="Cnae",
            fields=[
                ("codigo", models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name="Código")),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
            ],
            options={"db_table": "cnpj_cnae", "verbose_name": "CNAE", "ordering": ["codigo"]},
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                ("codigo", models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name="Código")),
                ("descricao", models.CharField(max_length=60, verbose_name="Descrição")),
            ],
            options={"db_table": "cnpj_municipio", "verbose_name": "Município", "ordering": ["descricao"]},
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("codigo", models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name="Código")),
                ("descricao", models.CharField(max_length=70, verbose_name="Descrição")),
            ],
            options={"db_table": "cnpj_pais", "verbose_name": "País", "ordering": ["descricao"]},
        ),
        migrations.CreateModel(
            name="Natureza",
            fields=[
                ("codigo", models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name="Código")),
                ("descricao", models.CharField(max_length=100, verbose_name="Descrição")),
            ],
            options={"db_table": "cnpj_natureza", "verbose_name": "Natureza Jurídica"},
        ),
        migrations.CreateModel(
            name="Qualificacao",
            fields=[
                ("codigo", models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name="Código")),
                ("descricao", models.CharField(max_length=100, verbose_name="Descrição")),
            ],
            options={"db_table": "cnpj_qualificacao", "verbose_name": "Qualificação"},
        ),
        migrations.CreateModel(
            name="Motivo",
            fields=[
                ("codigo", models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name="Código")),
                ("descricao", models.CharField(max_length=100, verbose_name="Descrição")),
            ],
            options={"db_table": "cnpj_motivo", "verbose_name": "Motivo de Situação Cadastral"},
        ),
        # ── Tabelas principais ────────────────────────────────────────
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cnpj_basico", models.CharField(db_index=True, max_length=8, verbose_name="CNPJ Básico")),
                ("razao_social", models.CharField(blank=True, max_length=150, null=True, verbose_name="Razão Social")),
                ("natureza_juridica", models.CharField(blank=True, max_length=4, null=True, verbose_name="Natureza Jurídica")),
                ("qualificacao_responsavel", models.CharField(blank=True, max_length=2, null=True, verbose_name="Qualificação do Responsável")),
                ("capital_social", models.CharField(blank=True, max_length=20, null=True, verbose_name="Capital Social")),
                ("porte", models.CharField(blank=True, max_length=2, null=True, verbose_name="Porte")),
                ("ente_federativo_responsavel", models.CharField(blank=True, max_length=50, null=True, verbose_name="Ente Federativo Responsável")),
                ("competencia", models.CharField(db_index=True, max_length=7, verbose_name="Competência")),
            ],
            options={"db_table": "cnpj_empresa", "verbose_name": "Empresa"},
        ),
        migrations.AddIndex(
            model_name="empresa",
            index=models.Index(fields=["cnpj_basico", "competencia"], name="idx_empresa_cnpj_comp"),
        ),
        migrations.CreateModel(
            name="Estabelecimento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cnpj_basico", models.CharField(db_index=True, max_length=8, verbose_name="CNPJ Básico")),
                ("cnpj_ordem", models.CharField(max_length=4, verbose_name="CNPJ Ordem")),
                ("cnpj_dv", models.CharField(max_length=2, verbose_name="CNPJ DV")),
                ("identificador_matriz_filial", models.CharField(blank=True, max_length=1, null=True, verbose_name="Matriz/Filial")),
                ("nome_fantasia", models.CharField(blank=True, max_length=55, null=True, verbose_name="Nome Fantasia")),
                ("situacao_cadastral", models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name="Situação Cadastral")),
                ("data_situacao_cadastral", models.DateField(blank=True, null=True, verbose_name="Data Situação Cadastral")),
                ("motivo_situacao_cadastral", models.CharField(blank=True, max_length=2, null=True, verbose_name="Motivo Situação Cadastral")),
                ("nome_cidade_exterior", models.CharField(blank=True, max_length=55, null=True, verbose_name="Nome Cidade Exterior")),
                ("pais", models.CharField(blank=True, max_length=3, null=True, verbose_name="País")),
                ("data_inicio_atividade", models.DateField(blank=True, null=True, verbose_name="Data Início Atividade")),
                ("cnae_fiscal_principal", models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name="CNAE Fiscal Principal")),
                ("cnae_fiscal_secundaria", models.TextField(blank=True, null=True, verbose_name="CNAEs Secundários")),
                ("tipo_logradouro", models.CharField(blank=True, max_length=20, null=True, verbose_name="Tipo Logradouro")),
                ("logradouro", models.CharField(blank=True, max_length=60, null=True, verbose_name="Logradouro")),
                ("numero", models.CharField(blank=True, max_length=6, null=True, verbose_name="Número")),
                ("complemento", models.CharField(blank=True, max_length=156, null=True, verbose_name="Complemento")),
                ("bairro", models.CharField(blank=True, max_length=50, null=True, verbose_name="Bairro")),
                ("cep", models.CharField(blank=True, max_length=8, null=True, verbose_name="CEP")),
                ("uf", models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name="UF")),
                ("municipio", models.CharField(blank=True, db_index=True, max_length=7, null=True, verbose_name="Município (código)")),
                ("ddd1", models.CharField(blank=True, max_length=4, null=True, verbose_name="DDD 1")),
                ("telefone1", models.CharField(blank=True, max_length=8, null=True, verbose_name="Telefone 1")),
                ("ddd2", models.CharField(blank=True, max_length=4, null=True, verbose_name="DDD 2")),
                ("telefone2", models.CharField(blank=True, max_length=8, null=True, verbose_name="Telefone 2")),
                ("ddd_fax", models.CharField(blank=True, max_length=4, null=True, verbose_name="DDD Fax")),
                ("fax", models.CharField(blank=True, max_length=8, null=True, verbose_name="Fax")),
                ("correio_eletronico", models.CharField(blank=True, max_length=115, null=True, verbose_name="E-mail")),
                ("situacao_especial", models.CharField(blank=True, max_length=23, null=True, verbose_name="Situação Especial")),
                ("data_situacao_especial", models.DateField(blank=True, null=True, verbose_name="Data Situação Especial")),
                ("competencia", models.CharField(db_index=True, max_length=7, verbose_name="Competência")),
            ],
            options={"db_table": "cnpj_estabelecimento", "verbose_name": "Estabelecimento"},
        ),
        migrations.AddIndex(
            model_name="estabelecimento",
            index=models.Index(fields=["cnpj_basico", "competencia"], name="idx_estab_cnpj_comp"),
        ),
        migrations.AddIndex(
            model_name="estabelecimento",
            index=models.Index(fields=["uf", "municipio"], name="idx_estab_uf_municipio"),
        ),
        migrations.CreateModel(
            name="Socio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cnpj_basico", models.CharField(db_index=True, max_length=8, verbose_name="CNPJ Básico")),
                ("identificador_socio", models.CharField(blank=True, max_length=1, null=True, verbose_name="Identificador do Sócio")),
                ("nome_socio", models.CharField(blank=True, max_length=150, null=True, verbose_name="Nome do Sócio")),
                ("cnpj_cpf_socio", models.CharField(blank=True, max_length=14, null=True, verbose_name="CNPJ/CPF do Sócio (mascarado)")),
                ("qualificacao_socio", models.CharField(blank=True, max_length=2, null=True, verbose_name="Qualificação do Sócio")),
                ("data_entrada_sociedade", models.DateField(blank=True, null=True, verbose_name="Data Entrada na Sociedade")),
                ("pais", models.CharField(blank=True, max_length=3, null=True, verbose_name="País")),
                ("representante_legal", models.CharField(blank=True, max_length=11, null=True, verbose_name="CPF Representante Legal")),
                ("nome_representante", models.CharField(blank=True, max_length=60, null=True, verbose_name="Nome do Representante")),
                ("qualificacao_representante", models.CharField(blank=True, max_length=2, null=True, verbose_name="Qualificação Representante")),
                ("faixa_etaria", models.CharField(blank=True, max_length=1, null=True, verbose_name="Faixa Etária")),
                ("competencia", models.CharField(db_index=True, max_length=7, verbose_name="Competência")),
            ],
            options={"db_table": "cnpj_socio", "verbose_name": "Sócio"},
        ),
        migrations.AddIndex(
            model_name="socio",
            index=models.Index(fields=["cnpj_basico", "competencia"], name="idx_socio_cnpj_comp"),
        ),
        migrations.CreateModel(
            name="Simples",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("cnpj_basico", models.CharField(db_index=True, max_length=8, verbose_name="CNPJ Básico")),
                ("opcao_simples", models.CharField(blank=True, max_length=1, null=True, verbose_name="Opção Simples")),
                ("data_opcao_simples", models.DateField(blank=True, null=True, verbose_name="Data Opção Simples")),
                ("data_exclusao_simples", models.DateField(blank=True, null=True, verbose_name="Data Exclusão Simples")),
                ("opcao_mei", models.CharField(blank=True, max_length=1, null=True, verbose_name="Opção MEI")),
                ("data_opcao_mei", models.DateField(blank=True, null=True, verbose_name="Data Opção MEI")),
                ("data_exclusao_mei", models.DateField(blank=True, null=True, verbose_name="Data Exclusão MEI")),
                ("competencia", models.CharField(db_index=True, max_length=7, verbose_name="Competência")),
            ],
            options={"db_table": "cnpj_simples", "verbose_name": "Simples Nacional / MEI"},
        ),
        migrations.AddIndex(
            model_name="simples",
            index=models.Index(fields=["cnpj_basico", "competencia"], name="idx_simples_cnpj_comp"),
        ),
        # ── Auditoria ─────────────────────────────────────────────────
        migrations.CreateModel(
            name="CargaLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("arquivo", models.CharField(max_length=80, verbose_name="Arquivo")),
                ("competencia", models.CharField(db_index=True, max_length=7, verbose_name="Competência")),
                ("qtd_registros", models.BigIntegerField(default=0, verbose_name="Qtd. Registros")),
                ("status", models.CharField(choices=[("INICIADO", "Iniciado"), ("SUCESSO", "Sucesso"), ("ERRO", "Erro"), ("PARCIAL", "Parcial")], default="INICIADO", max_length=10, verbose_name="Status")),
                ("inicio", models.DateTimeField(auto_now_add=True, verbose_name="Início")),
                ("fim", models.DateTimeField(blank=True, null=True, verbose_name="Fim")),
                ("erro", models.TextField(blank=True, null=True, verbose_name="Mensagem de Erro")),
            ],
            options={"db_table": "cnpj_carga_log", "verbose_name": "Log de Carga", "ordering": ["-inicio"]},
        ),
    ]
