# Generated by Django 4.2.19 on 2026-02-21 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0001_initial'),
    ]

    operations = [
    ]
