# Generated by Django 4.2.19 on 2026-02-21 03:20

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0002_auto_20260221_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargalog',
            options={'ordering': ['-inicio'], 'verbose_name': 'Log de Carga', 'verbose_name_plural': 'Logs de Carga'},
        ),
        migrations.AlterModelOptions(
            name='cnae',
            options={'ordering': ['codigo'], 'verbose_name': 'CNAE', 'verbose_name_plural': 'CNAEs'},
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='estabelecimento',
            options={'verbose_name': 'Estabelecimento', 'verbose_name_plural': 'Estabelecimentos'},
        ),
        migrations.AlterModelOptions(
            name='motivo',
            options={'ordering': ['codigo'], 'verbose_name': 'Motivo de Situação Cadastral', 'verbose_name_plural': 'Motivos de Situação Cadastral'},
        ),
        migrations.AlterModelOptions(
            name='municipio',
            options={'ordering': ['descricao'], 'verbose_name': 'Município', 'verbose_name_plural': 'Municípios'},
        ),
        migrations.AlterModelOptions(
            name='natureza',
            options={'ordering': ['codigo'], 'verbose_name': 'Natureza Jurídica', 'verbose_name_plural': 'Naturezas Jurídicas'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['descricao'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='qualificacao',
            options={'ordering': ['codigo'], 'verbose_name': 'Qualificação', 'verbose_name_plural': 'Qualificações'},
        ),
        migrations.AlterModelOptions(
            name='simples',
            options={'verbose_name': 'Simples Nacional / MEI', 'verbose_name_plural': 'Simples Nacional / MEI'},
        ),
        migrations.AlterModelOptions(
            name='socio',
            options={'verbose_name': 'Sócio', 'verbose_name_plural': 'Sócios'},
        ),
        migrations.AlterField(
            model_name='cargalog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='estabelecimento',
            name='situacao_especial',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Situação Especial'),
        ),
        migrations.AlterField(
            model_name='simples',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=django.contrib.postgres.indexes.GinIndex(fields=['razao_social'], name='idx_empresa_razao_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
