# Generated by Django 4.2.19 on 2026-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnpj', '0003_alter_cargalog_options_alter_cnae_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='estabelecimento',
            name='idx_estab_uf_municipio',
        ),
        migrations.AddIndex(
            model_name='estabelecimento',
            index=models.Index(fields=['uf', 'municipio', 'competencia'], name='idx_estab_uf_municipio'),
        ),
        migrations.AddIndex(
            model_name='estabelecimento',
            index=models.Index(fields=['cnae_fiscal_principal', 'competencia'], name='idx_estab_cnae_comp'),
        ),
        migrations.AddIndex(
            model_name='estabelecimento',
            index=models.Index(fields=['situacao_cadastral', 'competencia'], name='idx_estab_sit_comp'),
        ),
        migrations.AddIndex(
            model_name='simples',
            index=models.Index(fields=['opcao_simples', 'opcao_mei', 'competencia'], name='idx_simples_opcoes_comp'),
        ),
    ]
