# Generated by Django 4.2.19 on 2026-03-03 14:49

from django.db import migrations


from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
    ]
    
    # Roda primeiro de tudo: Cuidado pro django aplicar antes das tabelas de negócio!
    run_before = [
        ('cnpj', '0001_initial'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
    ]
